### ISSUE TITLE
Extension definiton in shoot with null values

### ISSUE THREAD

**Issue by lsroe** [gardener/gardener-extension-shoot-falco-service#141]
**What happened**:
If not provided, `falcoCtl` values are set to `null` in the shoot spec when not provided.

```yaml
  extensions:
    - type: shoot-falco-service
      providerConfig:
        apiVersion: falco.extensions.gardener.cloud/v1alpha1
        autoUpdate: true
        falcoCtl:
          allowedTypes: null
          indexes: null
        falcoVersion: 0.39.2
        gardener:
          useFalcoIncubatingRules: false
          useFalcoRules: true
          useFalcoSandboxRules: false
        kind: FalcoServiceConfig
        resources: gardener
        webhook:
          enabled: false
```

**What you expected to happen**:
If not provided, `falcoCtl` values shall have sensible defaults or be left blank 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:
