### ISSUE TITLE
Support compression for Falco rule files in config maps

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener-extension-shoot-falco-service#146]
**What would you like to be added**:

For security reasons config maps in Gardener project namespaces are restricted in size. We need a way to increase that size without compromising security. 

**Implementation proposal*:

Allow gzipped files to be added to the custom rule configmap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-custom-rules
  namespace: garden-myproject
data:
  custom-rules.yaml.gz: <base64 encoded gzipped file>
```

Care must be taken to limit the maximum size that is unpacked from the file. 1 MB sounds like a reasonable restriction. In this context it would be advisable to only allow a limited number of entries per configmap (something like 20).

**Why is this needed**:

We have reports that the maximum size is too small for custom rule files.
