### ISSUE TITLE
Change Structure of Falco configuration in shoot specification

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener-extension-shoot-falco-service#215]
Based on review results we will change the Falco configuration in the shoot specification:

The minimal configuration shall be 

```
spec:
  extensions:
  - type: shoot-falco-service
```

which is equivalent to

```
spec:
  extensions:
  - type: shoot-falco-service
    apiVersion: falco.extensions.gardener.cloud/v1alpha1
    kind: FalcoServiceConfig
```

and which will specify the following default configuration:

```
spec:
  extensions:
  - type: shoot-falco-service
    apiVersion: falco.extensions.gardener.cloud/v1alpha1
    kind: FalcoServiceConfig
    # latest Falco version tagged as "supported"
    falcoVersion: 0.40.0
    autoUpdate: true
    standardRules:
    - falco-rules
    events:
      destination:
      - logging    
```

The full structure is:

```
- type: shoot-falco-service
  providerConfig:
    apiVersion: falco.extensions.gardener.cloud/v1alpha1
    kind: FalcoServiceConfig
    
    # optional, will use the latest version tagged as "supported"
    falcoVersion: 0.40.0
    
    # optional, defaults to true
    autoUpdate: true | false
    
    # array of standard Falco rules from the Falco community. Possible array
    # elements are falco-rules, falco-incubating-rules, and falco-sandbox-rules
    # There is no default for this key unless and empty configuration was 
    # given
    standardRules:
    - falco-rules

    # references to configmaps in the `resources` section
    customRules:
    - my-rules

    events:
      # array of destinations, possible values are:
      # stdout, logging, central, custom
      # note that not all combinations are supported, e.g. central and custom
      # cannot be specified at the same time. Additional configuration is 
      # required ff destination is "custom" (see below)
      destination:
      - logging
```

If the destination is `custom` additional configuration is required: which 
configures the destination and possible access secrets.

```
    events:
      destination:
      - custom
      customConfig:
        - secret-resource-reference
```

Notes:
- The falcoctl feature requires a refactoring. It will be disabled and will
  not be available with a release that implements the propsed changes. The 
  will be a separate issue.
- The standard Falco rules provided by the Falco community do not depend on 
  each other. The ordering does not matter.
- It is likely that we will add additional destinations.

**Comment by ScheererJ** [comment]
Please fix the second and third examples. They are incorrect, `providerConfig` is missing.

I disagree with stating that providing no `providerConfig` is the same as providing an empty `providerConfig`. The extension should be able to deal with the case that there is simply no `providerConfig` with proper checks/defaulting.

Apart from that, I like the proposal.

**Comment by rfranzke** [comment]
I think the rules/config part could still be improved. Why not like this?

```yaml
- type: shoot-falco-service
  providerConfig:
    apiVersion: falco.extensions.gardener.cloud/v1alpha1
    kind: FalcoServiceConfig

    rules:
      standard:
      - name: falco-rules
      - name: ...
      custom:  
      - resourceName: my-rules # to make it clear that this is the reference to a resource defined in `.spec.resources[]`

    events:
      destinations:
        logging: {}
        custom:
          resourceName: my-secret-resource-ref # to make it clear that this is the reference to a resource defined in `.spec.resources[]`
```

Thoughts?

**Comment by rfranzke** [comment]
> we could not agree on the naming (and from @ScheererJ s point of view it is bad if you do not find a name).

Which naming? Can you elaborate?

> so although I generally agree with this point of view, this time it was mot entirely correct. We will look into it as it anyway is very close to our original proposal.

What does this mean?


Another question: Is the above example really the complete extension API spec? If yes, does it mean I can no longer specify a remote location for my rules (which previously under `.falcoCtl`)?

**Comment by marwinski** [comment]
> If yes, does it mean I can no longer specify a remote location for my rules (which previously under .falcoCtl)?

No, we do keep this feature but will refactor it.

**Comment by rfranzke** [comment]
In https://github.com/gardener/gardener-extension-shoot-falco-service/issues/215#issue-2949623939, you wrote

> The full structure is:

But apparently, this isn't true.
Please, specify the FULL **(!!!)** extension API specification here so that we can iterate on it. I would like to see it and perhaps provide feedback also on the remote option or other fields.

**Comment by marwinski** [comment]
Well, we initially proposed this:

```
    gardener:  ## OPEN FOR RENAMING;
      managedRules: ## NEW FIELD
        useFalcoIncubatingRules: true
        useFalcoRules: true
        useFalcoSandboxRules: false
      customRules:
        - falco-seed-exception-rules
        - falco-seed-exception-incubating-rules
```

This is not very elegant and the naming is questionable, agreed. @ScheererJ s argument was that if we cannot find a name for the root it is probably not good. Since we could not find a new name for `gardener` we agreed in the end to move rules to the top level but indeed, this is actually quite a good solution:

```
rules:
      standard:
      - name: falco-rules
      - name: ...
      custom:  
      - resourceName: my-rules 
````

which essentially replaces the use*Rules with a list and renames the root.
