### ISSUE TITLE
Add proper RBAC role for central storage access

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener-extension-shoot-falco-service#237]
**What would you like to be added**:

On central storage access we currently validate whether the requesting subject can do "get shoots". We need a proper role like the following:

```yaml
  - nonResourceURLs:
    - /api/events/v1alpha1
    verbs:
    - get
```

which can be checked by the Falco event ingestor. Rules lie`viewer` or `admin` should get this role automatically as well.

**Why is this needed**:

We need to doe separation of concerns. User that are allowed to read Falco event logs should not be able to access the Gardener and view shoot clusters - espeically not technical users with the purpose to genrate Falco event reports.
