### ISSUE TITLE
Extension shall support versioning policy

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener-extension-shoot-falco-service#28]
**What would you like to be added**:

A versioning policy that is roughly in line with the Gardener Kubernetes and operating system versioning policy shall be supported. For the following Falco versions this means:

```
  falcoVersions:
  - version: 0.37.0
    classification: deprecated
    expirationDate: "2024-05-20T23:59:59Z"
    rulesVersion: 3.0.1
  - version: 0.37.1
    classification: deprecated
    rulesVersion: 3.0.1
  - version: 0.38.0
    classification: supported
    rulesVersion: 3.0.1
```

- As of today (June 2024) version 0.37.0 cannot be used anymore because it is expired. Falco versions will be forcefully upgraded to 0.38.0 (the next supported version). 
- Version 0.37.1 is deprecated but can still be used. If auto-update is turned on this will be automatically upgraded to 0.38.0.

**Why is this needed**:

As we support multiple Falco versions, we need an update path similar to the Gardener Kubernetes and operating system updates.
